const fs = require('fs');
const path = require('path');

// Authoritative base data for all 118 elements
const elementsRaw = [
  // Period 1
  [1, "H", "Hydrogen", "هيدروجين", 1.008, "nonmetal", 1, 1, 1, 0, 1, "1s¹", 2.20, [1], "Big Bang nucleosynthesis (seconds after cosmos birth)", "تخليق الانفجار العظيم (بعد ثوانٍ من ولادة الكون)", ["Rocket fuel", "Ammonia synthesis", "Fuel cell clean energy"], ["وقود الصواريخ", "تخليق الأمونيا", "طاقة خلايا الوقود النظيفة"]],
  [2, "He", "Helium", "هيليوم", 4.0026, "noble", 1, 18, 2, 2, 2, "1s²", null, [2], "Stellar hydrogen core fusion & Big Bang", "اندماج الهيدروجين النجمي والانفجار العظيم", ["Cryogenics (MRI magnets)", "Deep sea diving breathing gas", "Atmospheric balloons"], ["التبريد العميق (مغناطيس الرنين)", "غاز تنفس الغوص العميق", "مناطيد الغلاف الجوي"]],

  // Period 2
  [3, "Li", "Lithium", "ليثيوم", 6.94, "alkali", 2, 1, 3, 4, 3, "[He] 2s¹", 0.98, [2, 1], "Cosmic ray spallation & Big Bang", "تشظي الأشعة الكونية والانفجار العظيم", ["Rechargeable EV batteries", "Mood stabilizing pharmaceuticals", "Specialized heat-resistant glass"], ["بطاريات السيارات الكهربائية", "أدوية استقرار المزاج", "زجاج مقاوم للحرارة العالية"]],
  [4, "Be", "Beryllium", "بريليوم", 9.0122, "alkaline", 2, 2, 4, 5, 4, "[He] 2s²", 1.57, [2, 2], "Cosmic ray spallation in interstellar space", "تشظي الأشعة الكونية في الفضاء بين النجوم", ["James Webb Space Telescope mirrors", "Aerospace structural alloys", "X-ray tube windows"], ["مرايا تلسكوب جيمس ويب", "سبائك الفضاء الهيكلية", "نوافذ أنابيب الأشعة السينية"]],
  [5, "B", "Boron", "بورون", 10.81, "metalloid", 2, 13, 5, 6, 5, "[He] 2s² 2p¹", 2.04, [2, 3], "Cosmic ray spallation", "تشظي الأشعة الكونية", ["Pyrex borosilicate glass", "Nuclear reactor neutron control rods", "Semiconductor dopant"], ["زجاج بايركس المقاوم", "قضبان التحكم النيوتروني بالمفاعلات", "إشابة أشباه الموصلات"]],
  [6, "C", "Carbon", "كربون", 12.011, "nonmetal", 2, 14, 6, 6, 6, "[He] 2s² 2p²", 2.55, [2, 4], "Triple-alpha process inside red giant stars", "عملية ألفا الثلاثية داخل النجوم العملاقة الحمراء", ["Basis of organic life and DNA", "Graphene and carbon nanotubes", "Structural carbon fibers"], ["أساس الحياة العضوية والحمض النووي", "الجرافين والأنابيب النانوية", "ألياف الكربون الهيكلية"]],
  [7, "N", "Nitrogen", "نيتروجين", 14.007, "nonmetal", 2, 15, 7, 7, 7, "[He] 2s² 2p³", 3.04, [2, 5], "CNO cycle hydrogen fusion in massive stars", "دورة CNO الاندماجية في النجوم الضخمة", ["Haber-Bosch industrial fertilizers", "Liquid nitrogen cryopreservation", "Food packaging inert gas"], ["أسمدة هابر-بوش الزراعية", "الحفظ بالنيتروجين السائل", "غاز خامل لحفظ الأغذية"]],
  [8, "O", "Oxygen", "أكسجين", 15.999, "nonmetal", 2, 16, 8, 8, 8, "[He] 2s² 2p⁴", 3.44, [2, 6], "Helium-carbon fusion in massive stars", "اندماج الهيليوم والكربون في النجوم العملاقة", ["Aerobic cellular respiration", "Steel manufacturing blast furnaces", "Rocket oxidizer for space travel"], ["التنفس الخلوي الهوائي", "أفران صهر وتصنيع الفولاذ", "مؤكسد وقود صواريخ الفضاء"]],
  [9, "F", "Fluorine", "فلور", 18.998, "halogen", 2, 17, 9, 10, 9, "[He] 2s² 2p⁵", 3.98, [2, 7], "Core-collapse supernovae & asymptotic giant branch stars", "مستعرات النجوم المنهارة وعمالقة AGB", ["Dental enamel prophylaxis", "Teflon non-stick PTFE fluoropolymer", "Uranium enrichment as UF6 gas"], ["وقاية مينا الأسنان", "بوليمر التيفلون المقاوم للالتصاق", "تخصيب اليورانيوم كغاز سادس الفلوريد"]],
  [10, "Ne", "Neon", "نيون", 20.180, "noble", 2, 18, 10, 10, 10, "[He] 2s² 2p⁶", null, [2, 8], "Carbon burning phase in massive stars", "مرحلة احتراق الكربون في النجوم الهائلة", ["High-voltage luminescent signs", "Helium-neon gas lasers", "Cryogenic refrigeration systems"], ["إعلانات الإضاءة الكهربائية العالية", "ليزر الهيليوم-نيون فائق الدقة", "أنظمة التبريد الكريوجيني"]],

  // Period 3
  [11, "Na", "Sodium", "صوديوم", 22.990, "alkali", 3, 1, 11, 12, 11, "[Ne] 3s¹", 0.93, [2, 8, 1], "Carbon burning in massive stellar cores", "احتراق الكربون في نوى النجوم الضخمة", ["Nerve impulse transmission (Na+/K+ pump)", "Sodium-ion grid energy batteries", "Nuclear fast reactor liquid coolant"], ["نقل النبضات العصبية الخلوية", "بطاريات الصوديوم للشبكات الكهربائية", "مبرد معدني سائل للمفاعلات السريعة"]],
  [12, "Mg", "Magnesium", "مغنيسيوم", 24.305, "alkaline", 3, 2, 12, 12, 12, "[Ne] 3s²", 1.31, [2, 8, 2], "Carbon and neon burning in massive stars", "احتراق الكربون والنيون في النجوم الضخمة", ["Central ion in chlorophyll for photosynthesis", "Ultralight automotive structural alloys", "Fireworks and flares pyrotechnics"], ["الأيون المركزي لكلوروفيل البناء الضوئي", "سبائك خفيفة الوزن لصناعة السيارات", "ألعاب نارية ومشاعل إضاءة"]],
  [13, "Al", "Aluminium", "ألومنيوم", 26.982, "post-transition", 3, 13, 13, 14, 13, "[Ne] 3s² 3p¹", 1.61, [2, 8, 3], "Neon burning and supernova nucleosynthesis", "احتراق النيون وتخليق المستعرات العظمى", ["Aviation and aerospace fuselages", "High-voltage transmission power lines", "Modern architecture and food packaging"], ["هياكل طائرات الطيران والفضاء", "خطوط نقل الكهرباء ذات الجهد العالي", "واجهات العمارة وتغليف الأغذية"]],
  [14, "Si", "Silicon", "سيليكون", 28.085, "metalloid", 3, 14, 14, 14, 14, "[Ne] 3s² 3p²", 1.90, [2, 8, 4], "Oxygen burning in massive stellar cores", "احتراق الأكسجين في نوى النجوم الضخمة", ["Microprocessors and semiconductor chips", "Photovoltaic solar energy cells", "Silicone biocompatible medical polymers"], ["المعالجات الدقيقة وشرائح السيليكون", "خلايا الطاقة الشمسية الكهروضوئية", "بوليمرات السيليكون الطبية"]],
  [15, "P", "Phosphorus", "فوسفور", 30.974, "nonmetal", 3, 15, 15, 16, 15, "[Ne] 3s² 3p³", 2.19, [2, 8, 5], "Neon burning and supernova shockwaves", "احتراق النيون وموجات صدمة السوبرنوفا", ["Cellular ATP energy currency & DNA backbone", "High-yield agricultural NPK fertilizers", "Match heads and safety pyrotechnics"], ["جزيئات ATP الحيوية وهيكل DNA", "أسمدة NPK الفوسفاتية الزراعية", "رؤوس أعواد الثقاب الآمنة"]],
  [16, "S", "Sulfur", "كبريت", 32.06, "nonmetal", 3, 16, 16, 16, 16, "[Ne] 3s² 3p⁴", 2.58, [2, 8, 6], "Oxygen burning in massive stars", "احتراق الأكسجين في النجوم الكبيرة", ["Sulfuric acid industrial chemical reagent", "Vulcanization of synthetic vehicle rubber", "Essential amino acids (cysteine & methionine)"], ["حمض الكبريتيك أهم الكيماويات الصناعية", "فلكنة المطاط لإطارات المركبات", "الأحماض الأمينية الأساسية للحياة"]],
  [17, "Cl", "Chlorine", "كلور", 35.45, "halogen", 3, 17, 17, 18, 17, "[Ne] 3s² 3p⁵", 3.16, [2, 8, 7], "Oxygen burning and supernova explosions", "احتراق الأكسجين وانفجارات السوبرنوفا", ["Global municipal drinking water disinfection", "PVC construction piping polymer", "Production of modern pharmaceuticals"], ["تطهير مياه الشرب البلدية حول العالم", "أنابيب البناء من بوليمر PVC", "تخليق المستحضرات الصيدلانية الحديثة"]],
  [18, "Ar", "Argon", "أرجون", 39.948, "noble", 3, 18, 18, 22, 18, "[Ne] 3s² 3p⁶", null, [2, 8, 8], "Decay of radioactive Potassium-40 in rocks & stars", "تحلل البوتاسيوم-40 المشع في الصخور والنجوم", ["TIG inert shield gas welding", "Double-glazed insulated thermal windows", "Titanium and silicon crystal manufacturing"], ["غاز حماية لحام القوس الكهربائي TIG", "نوافذ العزل الحراري المزدوجة", "تصنيع بلورات التيتانيوم والسيليكون"]],

  // Period 4
  [19, "K", "Potassium", "بوتاسيوم", 39.098, "alkali", 4, 1, 19, 20, 19, "[Ar] 4s¹", 0.82, [2, 8, 8, 1], "Supernova silicon burning phase", "مرحلة احتراق السيليكون في السوبرنوفا", ["Cardiac electrical action potential regulation", "Potash fertilizer for plant growth", "Potassium hydroxide industrial electrolyte"], ["تنظيم جهد الفعل الكهربائي للقلب", "أسمدة البوتاس الزراعية لنمو النبات", "إلكتروليت هيدروكسيد البوتاسيوم"]],
  [20, "Ca", "Calcium", "كالسيوم", 40.078, "alkaline", 4, 2, 20, 20, 20, "[Ar] 4s²", 1.00, [2, 8, 8, 2], "Silicon burning in pre-supernova stars", "احتراق السيليكون قبيل انفجار النجم", ["Vertebrate skeleton and tooth structural matrix", "Portland cement and concrete construction", "Cellular second-messenger signal cascades"], ["الهيكل العظمي والأسنان للفقاريات", "أسمنت بورتلاند والخرسانة المسلحة", "شلالات الإشارات الخلوية الثانوية"]],
  [21, "Sc", "Scandium", "سكانديوم", 44.956, "transition", 4, 3, 21, 24, 21, "[Ar] 3d¹ 4s²", 1.36, [2, 8, 9, 2], "Supernova core collapse shockwaves", "موجات صدمة انهيار قلب السوبرنوفا", ["High-performance MiG aerospace alloys", "High-intensity metal halide sports lighting", "Solid oxide fuel cell electrolytes"], ["سبائك طائرات ميج الفضائية فائقة القوة", "إضاءة الملاعب الرياضية الهاليدية", "إلكتروليت خلايا وقود الأكسيد الصلب"]],
  [22, "Ti", "Titanium", "تيتانيوم", 47.867, "transition", 4, 4, 22, 26, 22, "[Ar] 3d² 4s²", 1.54, [2, 8, 10, 2], "Silicon burning and explosive nucleosynthesis", "احتراق السيليكون والتخليق النووي الانفجاري", ["Biocompatible surgical implants and prosthetics", "Supersonic aircraft jet engine turbine blades", "Titanium dioxide opaque white pigment in paints"], ["المزروعات الجراحية والتعويضات الحيوية", "شفرات توربينات محركات الطائرات النفاثة", "صبغة ثاني أكسيد التيتانيوم البيضاء"]],
  [23, "V", "Vanadium", "فاناديوم", 50.942, "transition", 4, 5, 23, 28, 23, "[Ar] 3d³ 4s²", 1.63, [2, 8, 11, 2], "Supernova nucleosynthesis", "التخليق النووي في السوبرنوفا", ["Vanadium redox flow grid-storage batteries", "High-strength structural tool steel", "Chemical catalyst for sulfuric acid production"], ["بطاريات تدفق الفاناديوم للشبكات", "فولاذ الأدوات الهيكلي المقاوم للصدمات", "محفز كيميائي لإنتاج حمض الكبريتيك"]],
  [24, "Cr", "Chromium", "كروم", 51.996, "transition", 4, 6, 24, 28, 24, "[Ar] 3d⁵ 4s¹", 1.66, [2, 8, 13, 1], "Explosive silicon burning in supernovae", "احتراق السيليكون المتفجر في المستعرات", ["Stainless steel anticorrosive alloying agent", "Decorative electroplating on automobiles", "High-temperature refractory chrome bricks"], ["مكون سبائك الفولاذ المقاوم للصدأ", "الطلاء الكهربائي اللامع للسيارات", "طوب الكروم الحراري المقاوم للأفران"]],
  [25, "Mn", "Manganese", "منغنيز", 54.938, "transition", 4, 7, 25, 30, 25, "[Ar] 3d⁵ 4s²", 1.55, [2, 8, 13, 2], "Silicon burning and core collapse", "احتراق السيليكون وانهيار قلب النجم", ["Manganese-rich EV lithium battery cathodes", "Desulfurization in commercial steelmaking", "Water-splitting photosystem II cluster"], ["مهابط بطاريات الليثيوم للسيارات", "إزالة الكبريت في تصنيع الفولاذ", "عنقود شطر الماء في التمثيل الضوئي"]],
  [26, "Fe", "Iron", "حديد", 55.845, "transition", 4, 8, 26, 30, 26, "[Ar] 3d⁶ 4s²", 1.83, [2, 8, 14, 2], "Equilibrium nuclear peak in Type Ia & II supernovae", "ذروة الاستقرار النووي في السوبرنوفا", ["Hemoglobin oxygen transport protein in blood", "Global structural steel bridges and skyscrapers", "Planetary magnetic geodynamo core"], ["بروتين الهيموجلوبين لنقل الأكسجين بالدم", "جسور وناطحات السحاب الفولاذية", "المولد الجيوديناميكي لمجال الأرض المغناطيسي"]],
  [27, "Co", "Cobalt", "كوبالت", 58.933, "transition", 4, 9, 27, 32, 27, "[Ar] 3d⁷ 4s²", 1.88, [2, 8, 15, 2], "Supernova shockwave nucleosynthesis", "تخليق صدمات السوبرنوفا النووية", ["Lithium-ion energy storage battery cathodes", "Alnico permanent super-magnets", "Cobalt-60 cancer radiation oncology"], ["مهابط بطاريات الليثيوم عالية الكثافة", "مغانط ألنيكو الفائقة الدائمة", "كوبالت-60 لعلاج الأورام السرطانية بالإشعاع"]],
  [28, "Ni", "Nickel", "نيكل", 58.693, "transition", 4, 10, 28, 31, 28, "[Ar] 3d⁸ 4s²", 1.91, [2, 8, 16, 2], "Radioactive decay of stellar Nickel-56 in supernovae", "تحلل النيكل-56 المشع في السوبرنوفا", ["Superalloys for jet rocket turbines", "Rechargeable nickel-metal hydride batteries", "Corrosion-resistant marine hardware"], ["سبائك فائقة لتوربينات الصواريخ النفاثة", "بطاريات النيكل-هيدريد القابلة للشحن", "أجهزة مقاومة لتآكل مياه البحر"]],
  [29, "Cu", "Copper", "نحاس", 63.546, "transition", 4, 11, 29, 35, 29, "[Ar] 3d¹⁰ 4s¹", 1.90, [2, 8, 18, 1], "Slow neutron capture (s-process) in dying red giants", "الالتقاط النيوتروني البطيء (s-process)", ["High-conductivity electrical wiring grids", "Antimicrobial hospital surface touchpoints", "High-efficiency thermal heat exchangers"], ["أسلاك وشبكات نقل الكهرباء الفائقة", "أسطح المستشفيات المضادة للميكروبات", "مبادلات التبديد الحراري العالية الكفاءة"]],
  [30, "Zn", "Zinc", "زنك", 65.38, "transition", 4, 12, 30, 35, 30, "[Ar] 3d¹⁰ 4s²", 1.65, [2, 8, 18, 2], "Supernova explosive nucleosynthesis & s-process", "التخليق النووي الانفجاري ومسار s", ["Galvanization rust protection for steel", "Zinc-carbon & alkaline batteries", "Zinc finger DNA-binding protein transcription"], ["جلفنة الفولاذ للحماية من الصدأ", "البطاريات القلوية وبطاريات الزنك", "بروتينات أصابع الزنك لنسخ الجينات"]],
  [31, "Ga", "Gallium", "غاليوم", 69.723, "post-transition", 4, 13, 31, 39, 31, "[Ar] 3d¹⁰ 4s² 4p¹", 1.81, [2, 8, 18, 3], "Rapid & slow neutron capture in stars", "الالتقاط النيوتروني السريع والبطيء", ["Gallium Nitride (GaN) fast power transistors", "Blue and violet Blu-ray semiconductor lasers", "Low-melting thermal liquid metal pastes"], ["ترانزستورات نيتريد الغاليوم فائقة الكفاءة", "ليزر أشعة بلو راي الزرقاء والبنفسجية", "معاجين المعادن السائلة للتبديد الحراري"]],
  [32, "Ge", "Germanium", "جرمانيوم", 72.630, "metalloid", 4, 14, 32, 41, 32, "[Ar] 3d¹⁰ 4s² 4p²", 2.01, [2, 8, 18, 4], "Neutron capture in asymptotic giant branch stars", "الالتقاط النيوتروني في عمالقة النجوم", ["Infrared night-vision optical lenses", "Fiber-optic telecommunication cables", "High-speed SiGe integrated microchips"], ["عدسات بصريات الرؤية الليلية بالأشعة تحت الحمراء", "كابلات الاتصالات بالألياف الضوئية", "شرائح السيليكون-جرمانيوم الفائقة السرعة"]],
  [33, "As", "Arsenic", "زرنيخ", 74.922, "metalloid", 4, 15, 33, 42, 33, "[Ar] 3d¹⁰ 4s² 4p³", 2.18, [2, 8, 18, 5], "Neutron capture during core-collapse supernovae", "الالتقاط النيوتروني أثناء انهيار المستعر الأعظم", ["Gallium arsenide ultra-high-frequency radar", "Semiconductor n-type crystal doping", "High-efficiency space solar panels"], ["رادارات زرنيخيد الغاليوم فائقة التردد", "إشابة بلورات أشباه الموصلات من النوع n", "ألواح الطاقة الشمسية لمركبات الفضاء"]],
  [34, "Se", "Selenium", "سيلينيوم", 78.971, "nonmetal", 4, 16, 34, 45, 34, "[Ar] 3d¹⁰ 4s² 4p⁴", 2.55, [2, 8, 18, 6], "Supernova r-process & asymptotic giant stars", "مسار r في السوبرنوفا والنجوم العملاقة", ["Photocopier photoreceptor drums", "Glass decoloring and ruby red pigmentation", "Glutathione peroxidase antioxidant enzyme"], ["أسطوانات النسخ الضوئي الحساسة للضوء", "إزالة لون الزجاج وصبغات الياقوت الأحمر", "إنزيم مضاد الأكسدة الجلوتاثيون بيروكسيديز"]],
  [35, "Br", "Bromine", "بروم", 79.904, "halogen", 4, 17, 35, 45, 35, "[Ar] 3d¹⁰ 4s² 4p⁵", 2.96, [2, 8, 18, 7], "Stellar neutron capture reactions", "تفاعلات الالتقاط النيوتروني النجمية", ["Flame retardants for electronics and textiles", "Oil and gas drilling clear completion fluids", "Sedative pharmaceutical synthesis"], ["مثبطات اللهب للإلكترونيات والأقمشة", "سوائل حفر آبار النفط والغاز عالية الكثافة", "تخليق المهدئات والأدوية التخصصية"]],
  [36, "Kr", "Krypton", "كريبتون", 83.798, "noble", 4, 18, 36, 48, 36, "[Ar] 3d¹⁰ 4s² 4p⁶", 3.00, [2, 8, 18, 8], "Slow neutron capture in asymptotic giant branch stars", "الالتقاط النيوتروني البطيء في النجوم العملاقة", ["Airport runway high-intensity flash beacons", "Insulated laser windows & energy-efficient glazing", "Uranium nuclear fission yield tracking gas"], ["أضواء وميض مدارج المطارات عالية الشدة", "نوافذ الليزر المعزولة والزجاج الموفر للطاقة", "تتبع نواتج الانشطار النووي لليورانيوم"]],

  // Period 5
  [37, "Rb", "Rubidium", "روبيديوم", 85.468, "alkali", 5, 1, 37, 48, 37, "[Kr] 5s¹", 0.82, [2, 8, 18, 8, 1], "Supernova r-process and stellar s-process", "مسار r للسوبرنوفا والالتقاط البطيء", ["Bose-Einstein condensate quantum physics", "Atomic frequency clocks for GPS timing", "Photomultiplier vacuum tube photocathodes"], ["تكاثف بوز-أينشتاين للفيزياء الكمية", "ساعات التردد الذرية لنظام تحديد المواقع GPS", "المهابط الضوئية لأنابيب التكبير الفراغية"]],
  [38, "Sr", "Strontium", "سترونشيوم", 87.62, "alkaline", 5, 2, 38, 50, 38, "[Kr] 5s²", 0.95, [2, 8, 18, 8, 2], "Stellar s-process and neutron star mergers", "مسار s واندماج النجوم النيوترونية", ["Optical lattice ultra-precise atomic clocks", "Brilliant crimson fireworks and road flares", "Strontium-89 radionuclide bone cancer therapy"], ["ساعات الشبكة الضوئية الذرية فائقة الدقة", "ألعاب نارية قرمزية ساطعة ومشاعل طوارئ", "سترونشيوم-89 المشع لعلاج آلام سرطان العظام"]],
  [39, "Y", "Yttrium", "إتريوم", 88.906, "transition", 5, 3, 39, 50, 39, "[Kr] 4d¹ 5s²", 1.22, [2, 8, 18, 9, 2], "Neutron star kilonova mergers & supernovae", "اندماجات الكيلونوفا والمستعرات العظمى", ["YBCO high-temperature superconductors", "YAG medical and industrial laser crystals", "LED white lighting phosphor matrices"], ["الموصلات الفائقة YBCO في درجات الحرارة العالية", "بلورات ليزر YAG الطبية والصناعية", "مصفوفات الفوسفور لإضاءة LED البيضاء"]],
  [40, "Zr", "Zirconium", "زركونيوم", 91.224, "transition", 5, 4, 40, 51, 40, "[Kr] 4d² 5s²", 1.33, [2, 8, 18, 10, 2], "Asymptotic giant branch stars s-process", "مسار s في النجوم العملاقة المقاربة", ["Nuclear reactor uranium fuel rod cladding", "Cubic zirconia diamond-substitute gemstones", "Corrosion-proof chemical processing valves"], ["تغليف قضبان وقود اليورانيوم بالمفاعلات", "أحجار الزركونيا المكعبة البديلة للماس", "صمامات المعالجة الكيميائية المقاومة للتآكل"]],
  [41, "Nb", "Niobium", "نيوبيوم", 92.906, "transition", 5, 5, 41, 52, 41, "[Kr] 4d⁴ 5s¹", 1.6, [2, 8, 18, 12, 1], "Neutron star mergers and core collapse", "اندماج النجوم النيوترونية والانهيار اللبي", ["Large Hadron Collider superconducting magnets", "High-strength low-alloy structural steel", "Rocket thruster nozzle alloys"], ["مغانط مصادم الهادرونات الكبير فائقة التوصيل", "فولاذ السبائك العالي المقاومة للهياكل", "فوهات محركات دفع الصواريخ الفضائية"]],
  [42, "Mo", "Molybdenum", "موليبدنوم", 95.95, "transition", 5, 6, 42, 54, 42, "[Kr] 4d⁵ 5s¹", 2.16, [2, 8, 18, 13, 1], "Supernova r-process & stellar s-process", "مسار r في السوبرنوفا ومسار s النجمي", ["Parent radioisotope for Technetium-99m imaging", "High-temperature furnace heating elements", "Petroleum refining hydrodesulfurization catalyst"], ["النظير الأم لتصوير التكنيشيوم-99m الطبي", "عناصر تسخين الأفران الصناعية عالية الحرارة", "محفز إزالة الكبريت في تكرير النفط"]],
  [43, "Tc", "Technetium", "تكنيشيوم", 98.0, "transition", 5, 7, 43, 55, 43, "[Kr] 4d⁵ 5s²", 1.9, [2, 8, 18, 13, 2], "Synthetic via nuclear reactors & red giant stars", "مخلق في المفاعلات النووية ورصد في النجوم الحمراء", ["Technetium-99m 80% of all nuclear medicine scans", "Radiotracer for myocardial perfusion imaging", "Corrosion protection studies in nuclear metallurgy"], ["تكنيشيوم-99m لـ 80% من فحوصات الطب النووي عالمياً", "متتبع إشعاعي لتصوير نضح عضلة القلب", "دراسات حماية التآكل في التعدين النووي"]],
  [44, "Ru", "Ruthenium", "روثينيوم", 101.07, "transition", 5, 8, 44, 57, 44, "[Kr] 4d⁷ 5s¹", 2.2, [2, 8, 18, 15, 1], "Neutron star collisions and kilonova explosions", "اصطدامات النجوم النيوترونية وانفجارات الكيلونوفا", ["Hard disk drive perpendicular magnetic recording", "Ruthenium dye-sensitized solar cells (Grätzel)", "Chip interconnects for sub-3nm semiconductor nodes"], ["التسجيل المغناطيسي العمودي للأقراص الصلبة", "خلايا جراتزل الشمسية الصبغية الحساسة للضوء", "توصيلات الرقائق لأشباه الموصلات دون 3 نانومتر"]],
  [45, "Rh", "Rhodium", "روديوم", 102.91, "transition", 5, 9, 45, 58, 45, "[Kr] 4d⁸ 5s¹", 2.28, [2, 8, 18, 16, 1], "Neutron star mergers r-process", "مسار r الناتج عن اندماج النجوم النيوترونية", ["Automotive three-way catalytic converters (NOx reduction)", "High-reflectivity searchlight optical mirrors", "Electroplated tarnish-resistant luxury jewelry"], ["المحولات الحفازة للسيارات للحد من أكاسيد النيتروجين", "مرايا عاكسة فائقة لأضواء البحث البصرية", "طلاء المجوهرات الفاخرة لمنع التأكسد"]],
  [46, "Pd", "Palladium", "بلاديوم", 106.42, "transition", 5, 10, 46, 60, 46, "[Kr] 4d¹⁰", 2.20, [2, 8, 18, 18], "Kilonova mergers and supernova nucleosynthesis", "اندماج الكيلونوفا والتخليق النووي للمستعرات", ["Vehicle emission exhaust catalytic converters", "Hydrogen purification membranes (absorbs 900x vol)", "Multilayer ceramic capacitors in mobile phones"], ["محولات عوادم المركبات لتنقية الانبعاثات", "أغشية تنقية الهيدروجين (يمتص 900 ضعف حجمه)", "مكثفات السيراميك متعددة الطبقات بالهواتف"]],
  [47, "Ag", "Silver", "فضة", 107.87, "transition", 5, 11, 47, 61, 47, "[Kr] 4d¹⁰ 5s¹", 1.93, [2, 8, 18, 18, 1], "Colliding neutron stars (kilonovae)", "اصطدام النجوم النيوترونية (الكيلونوفا)", ["Highest electrical conductivity of any metal", "Solar photovoltaic cell silver conductive paste", "Antimicrobial wound dressings and medical catheters"], ["أعلى موصلية كهربائية وحرارية بين جميع المعادن", "معجون الفضة الموصل للخلايا الشمسية", "ضمادات الجروح والقساطر الطبية المضادة للبكتيريا"]],
  [48, "Cd", "Cadmium", "كادميوم", 112.41, "transition", 5, 12, 48, 64, 48, "[Kr] 4d¹⁰ 5s²", 1.69, [2, 8, 18, 18, 2], "Stellar s-process in giant stars & r-process", "مسار s في النجوم العملاقة ومسار r", ["Nickel-cadmium (NiCad) industrial batteries", "Quantum dots for QLED high-color displays", "Cadmium telluride (CdTe) thin-film solar panels"], ["بطاريات النيكل-كادميوم الصناعية", "النقاط الكمومية لشاشات QLED الزاهية", "ألواح الطاقة الشمسية ذات الأغشية الرقيقة CdTe"]],
  [49, "In", "Indium", "إنديوم", 114.82, "post-transition", 5, 13, 49, 66, 49, "[Kr] 4d¹⁰ 5s² 5p¹", 1.78, [2, 8, 18, 18, 3], "Rapid & slow neutron capture nucleosynthesis", "تخليق الالتقاط النيوتروني السريع والبطيء", ["Indium Tin Oxide (ITO) transparent smartphone touchscreens", "Low-temperature vacuum cryogenic hermetic seals", "Indium phosphide (InP) high-speed photonic chips"], ["أكسيد القصدير والإنديوم لشاشات اللمس الشفافة", "أختام الفراغ الكريوجيني منخفضة الحرارة", "رقائق فوسفيد الإنديوم الضوئية عالية السرعة"]],
  [50, "Sn", "Tin", "قصدير", 118.71, "post-transition", 5, 14, 50, 69, 50, "[Kr] 4d¹⁰ 5s² 5p²", 1.96, [2, 8, 18, 18, 4], "Stellar s-process in red giant branch stars", "مسار s في نجوم فرع العملاق الأحمر", ["Lead-free circuit board electronic solder alloys", "Corrosion-resistant tinplate food cans", "Niobium-tin superconducting MRI magnet wire"], ["سبائك لحام الدوائر الإلكترونية الخالية من الرصاص", "صفائح القصدير لتغليف الأغذية المحفوظة", "أسلاك النيوبيوم-قصدير لمغانط الرنين الفائقة"]],
  [51, "Sb", "Antimony", "إثمد", 121.76, "metalloid", 5, 15, 51, 71, 51, "[Kr] 4d¹⁰ 5s² 5p³", 2.05, [2, 8, 18, 18, 5], "Neutron capture during kilonovae & giant stars", "الالتقاط النيوتروني أثناء الكيلونوفا والنجوم", ["Flame retardant synergist (antimony trioxide)", "Lead-acid battery grid hardness enhancer", "Phase-change optical memory disks (DVD/Blu-ray)"], ["مثبط للهب في المواد البلاستيكية والأنسجة", "تعزيز صلابة شبكات بطاريات الرصاص الحمضية", "أقراص الذاكرة الضوئية متغيرة الطور"]],
  [52, "Te", "Tellurium", "تيلوريوم", 127.60, "metalloid", 5, 16, 52, 76, 52, "[Kr] 4d¹⁰ 5s² 5p⁴", 2.1, [2, 8, 18, 18, 6], "Kilonova mergers (abundant r-process peak)", "اندماجات الكيلونوفا (ذروة وفرة مسار r)", ["Cadmium telluride utility-scale solar farms", "Thermoelectric Peltier solid-state coolers", "Phase-change computer memory (PCRAM) chips"], ["مزارع الطاقة الشمسية الكهروضوئية CdTe", "مبردات بيلتيير الكهروحرارية بالحالة الصلبة", "رقائق ذاكرة الحاسوب متغيرة الطور PCRAM"]],
  [53, "I", "Iodine", "يود", 126.90, "halogen", 5, 17, 53, 74, 53, "[Kr] 4d¹⁰ 5s² 5p⁵", 2.66, [2, 8, 18, 18, 7], "Neutron star mergers (r-process nucleosynthesis)", "اندماج النجوم النيوترونية (التخليق النووي r)", ["Thyroid hormone regulation (T3 & T4 hormones)", "Iodinated radiocontrast agents for CT scans", "Iodine-131 targeted thyroid cancer radiotherapy"], ["تنظيم هرمونات الغدة الدرقية الحيوية", "مواد التباين الإشعاعي لفحوصات الأشعة المقطعية", "يود-131 للعلاج الإشعاعي الموجه لأورام الغدة"]],
  [54, "Xe", "Xenon", "زينون", 131.29, "noble", 5, 18, 54, 77, 54, "[Kr] 4d¹⁰ 5s² 5p⁶", 2.6, [2, 8, 18, 18, 8], "Neutron star mergers and core-collapse supernovae", "اندماج النجوم النيوترونية ومستعرات الانهيار", ["Ion thruster propellant for deep space probes (Dawn/Starlink)", "High-intensity vehicle HID headlight bulbs", "Liquid xenon particle detectors for Dark Matter searches (LUX/XENONnT)"], ["وقود محركات الدفع الأيوني لمسبارات الفضاء العميق", "مصابيح التفريغ عالية الكثافة HID للسيارات", "زينون سائل لكواشف أبحاث المادة المظلمة في الفيزياء"]],

  // Period 6
  [55, "Cs", "Caesium", "سيزيوم", 132.91, "alkali", 6, 1, 55, 78, 55, "[Xe] 6s¹", 0.79, [2, 8, 18, 18, 8, 1], "Neutron star mergers & slow neutron capture", "اندماج النجوم النيوترونية والالتقاط البطيء", ["Official SI unit of time: 9,192,631,770 Hz standard", "High-density caesium formate oil drilling fluids", "Caesium-137 industrial gamma irradiators"], ["المعيار الدولي لتعريف الثانية: 9.19 مليار ذبذبة", "سوائل فورمات السيزيوم لحفر آبار النفط العميقة", "سيزيوم-137 للتعقيم الإشعاعي الصناعي"]],
  [56, "Ba", "Barium", "باريوم", 137.33, "alkaline", 6, 2, 56, 81, 56, "[Xe] 6s²", 0.89, [2, 8, 18, 18, 8, 2], "Stellar s-process in asymptotic giant stars", "مسار s في النجوم العملاقة المقاربة", ["Barium sulfate GI tract diagnostic X-ray suspension", "Drilling mud weighting agent (barite)", "Green fireworks pyrotechnic emitters"], ["كبريتات الباريوم للتشخيص الشعاعي للجهاز الهضمي", "مادة تثقيل طين حفر آبار البترول (الباريت)", "اللون الأخضر المشع في الألعاب النارية"]],

  // Lanthanides (Row 8 display, logically Period 6)
  [57, "La", "Lanthanum", "لانثانوم", 138.91, "lanthanide", 8, 3, 57, 82, 57, "[Xe] 5d¹ 6s²", 1.10, [2, 8, 18, 18, 9, 2], "Neutron star collisions and asymptotic giant stars", "اصطدامات النجوم النيوترونية والعمالقة", ["Petroleum catalytic cracking catalysts for gasoline", "High-refractive index studio camera lenses", "Hybrid car battery nickel-metal hydride anodes"], ["محفزات التكسير الحفزي لإنتاج بنزين السيارات", "عدسات الكاميرات السينمائية ذات معامل الانكسار العالي", "أنودات بطاريات النيكل-هيدريد للسيارات الهجينة"]],
  [58, "Ce", "Cerium", "سيريوم", 140.12, "lanthanide", 8, 4, 58, 82, 58, "[Xe] 4f¹ 5d¹ 6s²", 1.12, [2, 8, 18, 19, 9, 2], "Stellar s-process in giant branch stars", "مسار s في نجوم فرع العمالقة", ["Cerium oxide precision glass polishing abrasive", "Automotive diesel fuel particulate filters", "Mischmetal for lighter flints and alloys"], ["أكسيد السيريوم لتلميع الزجاج والرقائق الدقيقة", "فلاتر جسيمات عوادم محركات الديزل للسيارات", "معدن الميش ميتال لصناعة حجر القداحات"]],
  [59, "Pr", "Praseodymium", "براسوديميوم", 140.91, "lanthanide", 8, 5, 59, 82, 59, "[Xe] 4f³ 6s²", 1.13, [2, 8, 18, 21, 8, 2], "Neutron capture in asymptotic giant branch stars", "الالتقاط النيوتروني في عمالقة النجوم", ["Didymium protective goggles for glassblowers", "High-power permanent aircraft neodymium magnets", "Fiber-optic optical signal amplification"], ["نظارات الديديميوم الواقية لنافخي الزجاج", "مغانط النيوديميوم الدائمة لمحركات الطائرات", "مضخمات الإشارات في كابلات الألياف الضوئية"]],
  [60, "Nd", "Neodymium", "نيوديميوم", 144.24, "lanthanide", 8, 6, 60, 84, 60, "[Xe] 4f⁴ 6s²", 1.14, [2, 8, 18, 22, 8, 2], "Neutron star mergers and supernova explosions", "اندماج النجوم النيوترونية والسوبرنوفا", ["NdFeB world strongest permanent magnets (EVs & wind turbines)", "Nd:YAG infrared surgical & industrial laser crystals", "High-fidelity audio headphone miniature drivers"], ["أقوى مغانط دائمة في العالم NdFeB للسيارات وتوربينات الرياح", "بلورات ليزر Nd:YAG للجراحة وتصنيع المعادن", "مشغلات سماعات الرأس الصوتية عالية الدقة"]],
  [61, "Pm", "Promethium", "بروميثيوم", 145.0, "lanthanide", 8, 7, 61, 84, 61, "[Xe] 4f⁵ 6s²", null, [2, 8, 18, 23, 8, 2], "Nuclear reactor uranium fission byproduct", "ناتج انشطار اليورانيوم في المفاعلات النووية", ["Atomic nuclear batteries for spacecraft and pacemakers", "Luminous dials for military gauges without power", "Beta radiation thickness measurement gauges"], ["بطاريات نووية ذرية لمركبات الفضاء وأجهزة تنظيم ضربات القلب", "أقراص مضيئة ذاتية لمعدات الطيران العسكري", "مقاييس سماكة المواد الصناعية بأشعة بيتا"]],
  [62, "Sm", "Samarium", "ساماريوم", 150.36, "lanthanide", 8, 8, 62, 88, 62, "[Xe] 4f⁶ 6s²", 1.17, [2, 8, 18, 24, 8, 2], "Kilonova mergers and asymptotic giant stars", "اندماجات الكيلونوفا والنجوم العملاقة", ["Samarium-cobalt (SmCo) high-temperature magnets", "Samarium-153 bone metastasis pain palliation", "Control rods in naval nuclear submarines"], ["مغانط الساماريوم-كوبالت المقاومة للحرارة الفائقة", "ساماريوم-153 لتسكين آلام نقائل العظام السرطانية", "قضبان التحكم النيوتروني في الغواصات النووية"]],
  [63, "Eu", "Europium", "يوروبيوم", 151.96, "lanthanide", 8, 9, 63, 89, 63, "[Xe] 4f⁷ 6s²", null, [2, 8, 18, 25, 8, 2], "Neutron star collision r-process nucleosynthesis", "تخليق الالتقاط السريع r في اصطدام النجوم النيوترونية", ["Euro banknote anti-counterfeiting phosphors", "Red phosphor emitter in color television and LED screens", "Quantum optical quantum memory experiments"], ["فوسفور مكافحة تزييف العملات الورقية لليورو", "المنبعث الفوسفوري الأحمر في شاشات التلفاز وLED", "تجارب الذاكرة الكمية في البصريات الكمومية"]],
  [64, "Gd", "Gadolinium", "غادولينيوم", 157.25, "lanthanide", 8, 10, 64, 93, 64, "[Xe] 4f⁷ 5d¹ 6s²", 1.20, [2, 8, 18, 25, 9, 2], "Kilonova explosions and stellar nucleosynthesis", "انفجارات الكيلونوفا والتخليق النووي النجمي", ["Paramagnetic contrast agent for MRI medical scans", "Highest thermal neutron capture cross-section for reactors", "Magnetocaloric magnetic refrigeration materials"], ["عامل التباين البارامغناطيسي للرنين المغناطيسي MRI", "أعلى مقطع التقاط نيوتروني حراري في المفاعلات", "مواد التبريد المغناطيسي الكالوري بدون غازات"]],
  [65, "Tb", "Terbium", "تيربيوم", 158.93, "lanthanide", 8, 11, 65, 94, 65, "[Xe] 4f⁹ 6s²", null, [2, 8, 18, 27, 8, 2], "Neutron star mergers r-process", "مسار r في اندماج النجوم النيوترونية", ["Terfenol-D magnetostrictive smart acoustic transducers", "Green phosphors for flat panel displays and tricolor lamps", "Solid-state laser light amplifiers"], ["محولات تيرفينول-دي الذكية للموجات الصوتية الدقيقة", "الفوسفور الأخضر للشاشات المسطحة والمصابيح ثلاثية الألوان", "مضخمات ضوء الليزر بالحالة الصلبة"]],
  [66, "Dy", "Dysprosium", "ديسبروسيوم", 162.50, "lanthanide", 8, 12, 66, 97, 66, "[Xe] 4f¹⁰ 6s²", 1.22, [2, 8, 18, 28, 8, 2], "Rapid neutron capture in colliding neutron stars", "الالتقاط النيوتروني السريع في النجوم المصطدمة", ["Demagnetization resistance additive in EV motor magnets", "Laser host crystal dopants and metal halide lamps", "Nuclear reactor control rod neutron absorbers"], ["إضافة مقاومة إزالة المغناطيسية لمحركات السيارات الكهربائية", "إشابة بلورات الليزر ومصابيح الهاليد المعدنية", "امتصاص النيوترونات في قضبان التحكم بالمفاعلات"]],
  [67, "Ho", "Holmium", "هولميوم", 164.93, "lanthanide", 8, 13, 67, 98, 67, "[Xe] 4f¹¹ 6s²", 1.23, [2, 8, 18, 29, 8, 2], "Neutron star mergers r-process", "مسار r لاندماجات النجوم النيوترونية", ["Highest magnetic moment of any natural element", "Holmium:YAG laser for kidney stone lithotripsy", "Single-atom magnetic memory research at IBM"], ["أعلى عزم مغناطيسي بين جميع العناصر الطبيعية", "ليزر هولميوم:YAG لتفتيت حصى الكلى الطبية بدقة", "أبحاث الذاكرة المغناطيسية للذرة الواحدة في IBM"]],
  [68, "Er", "Erbium", "إربيوم", 167.26, "lanthanide", 8, 14, 68, 99, 68, "[Xe] 4f¹² 6s²", 1.24, [2, 8, 18, 30, 8, 2], "Rapid neutron capture in kilonova mergers", "الالتقاط النيوتروني السريع في اندماج الكيلونوفا", ["Erbium-Doped Fiber Amplifiers (EDFA) powering global internet", "Er:YAG dermatology and cosmetic laser ablation", "Pink glass optical filters and jewelry glazes"], ["مضخمات الألياف EDFA التي تدير حركة الإنترنت العالمية", "ليزر Er:YAG الطبي لجراحة الجلد والتجميل", "مرشحات البصريات الزجاجية الوردية وطلاء الخزف"]],
  [69, "Tm", "Thulium", "ثوليوم", 168.93, "lanthanide", 8, 15, 69, 100, 69, "[Xe] 4f¹³ 6s²", 1.25, [2, 8, 18, 31, 8, 2], "Neutron star merger collisions", "اصطدامات اندماج النجوم النيوترونية", ["Portable field military X-ray generators", "High-efficiency 2-micron surgical laser systems", "Euro banknote security fluorescent dye pigments"], ["أجهزة الأشعة السينية المحمولة للميدان العسكري", "أنظمة الليزر الجراحي المتقدمة بطول موجي 2 ميكرون", "أصباغ الفلورسنت الأمنية لأوراق اليورو"]],
  [70, "Yb", "Ytterbium", "إتربيوم", 173.05, "lanthanide", 8, 16, 70, 103, 70, "[Xe] 4f¹⁴ 6s²", null, [2, 8, 18, 32, 8, 2], "Kilonova explosions and asymptotic giant stars", "انفجارات الكيلونوفا والنجوم العملاقة", ["Next-generation optical lattice atomic clocks", "High-power Ytterbium fiber lasers for industrial cutting", "Ytterbium-169 portable gamma ray radiography"], ["ساعات الشبكة الضوئية الذرية للجيل القادم", "ليزر ألياف الإتربيوم عالي الطاقة لقص المعادن الصناعي", "إتربيوم-169 للتصوير الإشعاعي بجاما للمعدات"]],
  [71, "Lu", "Lutetium", "لوتيتيوم", 174.97, "lanthanide", 8, 17, 71, 104, 71, "[Xe] 4f¹⁴ 5d¹ 6s²", 1.27, [2, 8, 18, 32, 9, 2], "Colliding neutron stars and stellar nucleosynthesis", "اصطدام النجوم النيوترونية والتخليق النجمي", ["Lutetium-177 targeted PSMA prostate cancer radiotherapy", "LSO crystal scintillators in PET medical scanners", "Petroleum refining hydrocarbon cracking catalysts"], ["لوتيتيوم-177 للعلاج الإشعاعي الموجه لسرطان البروستاتا", "بلورات كواشف LSO في أجهزة المسح المقطعي PET", "محفزات تكسير الهيدروكربونات في تكرير النفط"]],

  // Transition metals Period 6 continued
  [72, "Hf", "Hafnium", "هافنيوم", 178.49, "transition", 6, 4, 72, 106, 72, "[Xe] 4f¹⁴ 5d² 6s²", 1.30, [2, 8, 18, 32, 10, 2], "Neutron star mergers and rapid neutron capture", "اندماج النجوم النيوترونية والالتقاط السريع", ["High-k dielectric gate insulator in Intel/AMD CPU chips", "Nuclear submarine reactor control rods (corrosion-proof)", "Plasma arc cutting torch electrodes"], ["عازل البوابات عالي العزل الكهربائي في معالجات Intel و AMD", "قضبان التحكم بمفاعلات الغواصات النووية المقاومة للتآكل", "أقطاب شعلات القطع بقوس البلازما المعدنية"]],
  [73, "Ta", "Tantalum", "تانتالوم", 180.95, "transition", 6, 5, 73, 108, 73, "[Xe] 4f¹⁴ 5d³ 6s²", 1.50, [2, 8, 18, 32, 11, 2], "Stellar nucleosynthesis and kilonova explosions", "التخليق النووي النجمي وانفجارات الكيلونوفا", ["Miniature high-capacitance capacitors in 5G smartphones", "Corrosion-resistant chemical acid piping and reaction vessels", "Biocompatible skull bone plates and cranial implants"], ["مكثفات كهربائية ميكروية فائقة السعة بهواتف 5G", "أنابيب وخزانات التفاعلات الكيميائية المقاومة للأحماض", "صفائح عظام الجمجمة والمزروعات الطبية الحيوية"]],
  [74, "W", "Tungsten", "تنغستن", 183.84, "transition", 6, 6, 74, 110, 74, "[Xe] 4f¹⁴ 5d⁴ 6s²", 2.36, [2, 8, 18, 32, 12, 2], "Colliding neutron stars r-process", "اصطدام النجوم النيوترونية (مسار r)", ["Highest melting point of any metal (3,422 °C)", "ITER tokamak nuclear fusion reactor divertor armor tiles", "Kinetic energy armor-piercing anti-tank penetrators"], ["أعلى درجة انصهار لأي معدن في الطبيعة (3,422 مئوية)", "دروع محول مفاعل الاندماج النووي إيتر ITER", "مقذوفات الطاقة الحركية الخارقة للدروع العسكرية"]],
  [75, "Re", "Rhenium", "رينيوم", 186.21, "transition", 6, 7, 75, 111, 75, "[Xe] 4f¹⁴ 5d⁵ 6s²", 1.90, [2, 8, 18, 32, 13, 2], "Neutron star kilonova mergers", "اندماجات الكيلونوفا النجمية النيوترونية", ["Nickel single-crystal superalloys for jet engine combustors", "Lead-free high-octane gasoline reformate catalysts", "High-temperature thermocouple pyrometers for space rockets"], ["سبائك النيكل أحادية البلورة لغرف احتراق محركات النفاثات", "محفزات إنتاج بنزين السيارات عالي الأوكتان", "مزدوجات حرارية لقياس الحرارة الفائقة بصواريخ الفضاء"]],
  [76, "Os", "Osmium", "أوزميوم", 190.23, "transition", 6, 8, 76, 114, 76, "[Xe] 4f¹⁴ 5d⁶ 6s²", 2.20, [2, 8, 18, 32, 14, 2], "Kilonova mergers and explosive stellar r-process", "اندماج الكيلونوفا ومسار r النجمي الانفجاري", ["Densest naturally occurring element on Earth (22.59 g/cm³)", "Wear-resistant fountain pen nibs and electrical instrument pivots", "Osmium tetroxide staining for electron microscopy of lipids"], ["أكثف عنصر طبيعي على سطح الأرض (22.59 جم/سم مكعب)", "ريش أقلام الحبر الفاخرة ومحاور الأجهزة الدقيقة المقاومة للتآكل", "صبغة رابع أكسيد الأوزميوم للمجهر الإلكتروني للدهون"]],
  [77, "Ir", "Iridium", "إيريديوم", 192.22, "transition", 6, 9, 77, 115, 77, "[Xe] 4f¹⁴ 5d⁷ 6s²", 2.20, [2, 8, 18, 32, 15, 2], "Neutron star collisions (KT boundary asteroid marker)", "اصطدام النجوم النيوترونية (علامة نيزك انقراض الديناصورات)", ["Crucibles for growing high-purity laser single crystals", "Proton Exchange Membrane (PEM) green hydrogen electrolyzers", "Long-life aviation spark plug tips"], ["بواتق صهر لإنتاج بلورات الليزر أحادية النقاء العالية", "محللات الهيدروجين الأخضر الكهرومائية PEM", "شمعات اشتعال محركات الطائرات طويلة العمر"]],
  [78, "Pt", "Platinum", "بلاتين", 195.08, "transition", 6, 10, 78, 117, 78, "[Xe] 4f¹⁴ 5d⁹ 6s¹", 2.28, [2, 8, 18, 32, 17, 1], "Colliding neutron stars and kilonova events", "اصطدام النجوم النيوترونية وأحداث الكيلونوفا", ["Cisplatin and carboplatin life-saving cancer chemotherapy", "Hydrogen fuel cell zero-emission vehicle catalysts", "Immune to oxidation in biomedical pacemaker leads"], ["أدوية سيسبلاتين وكاربoplatin الكيميائية لعلاج الأورام", "محفزات خلايا وقود الهيدروجين لمركبات خالية من الانبعاثات", "أسلاك أجهزة تنظيم ضربات القلب المقاومة للتأكسد"]],
  [79, "Au", "Gold", "ذهب", 196.97, "transition", 6, 11, 79, 118, 79, "[Xe] 4f¹⁴ 5d¹⁰ 6s¹", 2.54, [2, 8, 18, 32, 18, 1], "Neutron star mergers detected by LIGO gravitational waves", "اندماج النجوم النيوترونية المرصود بموجات ليغو الثقالية", ["Microscopic wire bonding in every computer chip", "Infrared reflective coating on James Webb Space Telescope mirrors", "Global monetary reserve standard and luxury jewelry"], ["أسلاك الربط المجهرية داخل كل معالج حاسوبي", "الطلاء العاكس للأشعة تحت الحمراء بمرايا تلسكوب ويب", "احتياطي النقد والسيولة المالية العالمي والمجوهرات"]],
  [80, "Hg", "Mercury", "زئبق", 200.59, "transition", 6, 12, 80, 121, 80, "[Xe] 4f¹⁴ 5d¹⁰ 6s²", 2.00, [2, 8, 18, 32, 18, 2], "Kilonova mergers and supernova nucleosynthesis", "اندماجات الكيلونوفا والتخليق النووي في السوبرنوفا", ["Only metallic element liquid at standard room temperature", "Fluorescent energy-efficient commercial lighting tubes", "Amalgams for dental restorations and polarography"], ["المعدن الوحيد في الجدول الدوري السائل في حرارة الغرفة", "أنابيب الإضاءة الفلورية التجارية الموفرة للطاقة", "حشوات الأسنان الملغمية والأقطاب الكهربائية الحساسة"]],
  [81, "Tl", "Thallium", "ثاليوم", 204.38, "post-transition", 6, 13, 81, 123, 81, "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", 1.62, [2, 8, 18, 32, 18, 3], "Rapid neutron capture in kilonova explosions", "الالتقاط النيوتروني السريع في انفجارات الكيلونوفا", ["Thallium-201 nuclear medicine cardiac stress scintigraphy", "Infrared optical lenses and high-density optical glasses", "High-temperature cuprate superconductor components"], ["ثاليوم-201 لتصوير إجهاد القلب بالطب النووي", "عدسات البصريات للأشعة تحت الحمراء والزجاج العالي الكثافة", "مكونات الموصلات الفائقة النحاسية عالية الحرارة"]],
  [82, "Pb", "Lead", "رصاص", 207.2, "post-transition", 6, 14, 82, 125, 82, "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", 2.33, [2, 8, 18, 32, 18, 4], "Terminal stable decay product of Uranium & Thorium", "الناتج المستقر النهائي لتحلل اليورانيوم والثوريوم المشع", ["X-ray and gamma radiation shielding in hospitals and reactors", "Lead-acid starter batteries in over 1 billion vehicles globally", "Perovskite lead halide high-efficiency solar cells"], ["دروع الوقاية من أشعة إكس وجاما بالمستشفيات والمفاعلات", "بطاريات الرصاص لبدء تشغيل أكثر من مليار مركبة عالمياً", "خلايا بيروفسكايت الشمسية الحديثة فائقة الكفاءة"]],
  [83, "Bi", "Bismuth", "بزموت", 208.98, "post-transition", 6, 15, 83, 126, 83, "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", 2.02, [2, 8, 18, 32, 18, 5], "Slow neutron capture in asymptotic giant branch stars", "الالتقاط النيوتروني البطيء في النجوم العملاقة", ["Pepto-Bismol gastrointestinal soothing medications", "Non-toxic lead replacement in ammunition and plumbing", "Bismuth telluride solid-state thermoelectric coolers"], ["أدوية بيبتو-بيزمول لتهدئة اضطرابات الجهاز الهضمي", "بديل الرصاص غير السام في الذخائر والسباكة الحديثة", "مبردات تيلوريد البزموت الكهروحرارية الصلبة"]],
  [84, "Po", "Polonium", "بولونيوم", 209.0, "metalloid", 6, 16, 84, 125, 84, "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", 2.0, [2, 8, 18, 32, 18, 6], "Radioactive decay chain of natural Uranium-238", "سلسلة التحلل الإشعاعي لليورانيوم-238 الطبيعي", ["Antistatic ionizing brushes for cleanroom semiconductor wafers", "Radioisotope thermoelectric generators (RTG) for Moon rovers", "Neutron trigger source in early atomic weapons"], ["فراشي تفريغ الكهرباء الساكنة لرقائق أشباه الموصلات", "مولدات كهرباء النظائر الحرارية لمركبات استكشاف القمر", "مصدر إطلاق النيوترونات في الأسلحة الذرية المبكرة"]],
  [85, "At", "Astatine", "أستاتين", 210.0, "halogen", 6, 17, 85, 125, 85, "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", 2.2, [2, 8, 18, 32, 18, 7], "Rarest natural element in Earth crust (<1 gram total)", "أندر عنصر طبيعي في القشرة الأرضية (أقل من غرام واحد)", ["Targeted Alpha Therapy (TAT) for curing metastatic cancers", "Short-range high-LET localized cell tumor destruction", "Radio-halogen chemical bond research"], ["العلاج الإشعاعي المستهدف بألفا (TAT) للسرطانات النقيلية", "تدمير خلايا الأورام بنطاق موضعي فائق الدقة دون أذية السليم", "أبحاث الروابط الكيميائية للهالوجينات المشعة"]],
  [86, "Rn", "Radon", "رادون", 222.0, "noble", 6, 18, 86, 136, 86, "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", null, [2, 8, 18, 32, 18, 8], "Radioactive decay of Radium-226 in Earth granites", "تحلل الراديوم-226 المشع في صخور الجرانيت الأرضية", ["Earthquake fault slip tracking via soil gas release", "Historical brachytherapy cancer radiation seeds", "Indoor air quality environmental radiological monitoring"], ["تتبع حركة فوالق الزلازل عبر انبعاثات غاز التربة", "بذور العلاج الإشعاعي الموضعي للأورام قديماً", "مراقبة جودة الهواء الإشعاعي في المباني السكنية"]],

  // Period 7
  [87, "Fr", "Francium", "فرانسيوم", 223.0, "alkali", 7, 1, 87, 136, 87, "[Rn] 7s¹", 0.70, [2, 8, 18, 32, 18, 8, 1], "Radioactive decay of Uranium-235 in nature", "التحلل الإشعاعي لليورانيوم-235 في الطبيعة", ["Laser magneto-optical cooling atom traps", "Testing Standard Model parity non-conservation in weak force", "Atomic physics fundamental symmetry benchmarks"], ["مصائد الذرات بالتبريد المغناطيسي البصري بالليزر", "اختبارات كسر التناظر في القوة النووية الضعيفة", "معايير التناظر الأساسية في الفيزياء الذرية"]],
  [88, "Ra", "Radium", "راديوم", 226.0, "alkaline", 7, 2, 88, 138, 88, "[Rn] 7s²", 0.90, [2, 8, 18, 32, 18, 8, 2], "Decay of natural Uranium-238 discovered by Marie Curie", "تحلل اليورانيوم المشع واكتشفته ماري كوري", ["Radium-223 dichloride (Xofigo) for bone prostate metastases", "Historic self-luminous watch dials and flight instruments", "Industrial gamma source for oil well exploration"], ["راديوم-223 (زوفيجو) لعلاج نقائل سرطان البروستاتا العظمية", "ساعات الطيران المضيئة ذاتياً في القرن العشرين", "مصدر أشعة جاما لاستكشاف آبار النفط الجيولوجية"]],

  // Actinides (Row 9 display, logically Period 7)
  [89, "Ac", "Actinium", "أكتينيوم", 227.0, "actinide", 9, 3, 89, 138, 89, "[Rn] 6d¹ 7s²", 1.10, [2, 8, 18, 32, 18, 9, 2], "Radioactive decay chain of natural Uranium-235", "سلسلة التحلل الإشعاعي لليورانيوم-235 الطبيعي", ["Actinium-225 groundbreaking Targeted Alpha Therapy for cancer", "Thermoelectric radioisotope power in deep space equipment", "Neutron generator source when mixed with beryllium"], ["أكتينيوم-225 الرائد عالمياً في علاج السرطان بأشعة ألفا", "طاقة النظائر المشعة الكهروحرارية لمعدات الفضاء", "مصدر توليد النيوترونات عند خلطه بالبريليوم"]],
  [90, "Th", "Thorium", "ثوريوم", 232.04, "actinide", 9, 4, 90, 142, 90, "[Rn] 6d² 7s²", 1.30, [2, 8, 18, 32, 18, 10, 2], "Colliding neutron stars and primordial terrestrial deposits", "اصطدام النجوم النيوترونية والترسبات الأرضية البدائية", ["Molten Salt Thorium Nuclear Reactors (safer proliferation-free power)", "High-temperature gas mantle illumination", "Tungsten inert gas welding electrode alloy"], ["مفاعلات الثوريوم والملح المنصهر (طاقة نووية آمنة وغير قابلة للانتشار)", "أردية الإضاءة الغازية عالية التوهج والحرارة", "سبائك أقطاب لحام التنجستن بالقوس الخامل"]],
  [91, "Pa", "Protactinium", "بروتكتينيوم", 231.04, "actinide", 9, 5, 91, 140, 91, "[Rn] 5f² 6d¹ 7s²", 1.50, [2, 8, 18, 32, 20, 9, 2], "Intermediate in radioactive decay of Uranium-235", "عنصر وسيط في تحلل اليورانيوم-235 الطبيعي", ["Radiometric dating of deep marine ocean sediments", "Nuclear fuel breeding intermediate in thorium cycle", "Scientific research on 5f actinide electron chemistry"], ["التأريخ الإشعاعي لترسبات أعماق المحيطات البحرية", "وسيط إنتاج الوقود النووي في دورة وقود الثوريوم", "أبحاث كيمياء مدارات 5f الإلكترونية لسلسلة الأكتينيدات"]],
  [92, "U", "Uranium", "يورانيوم", 238.03, "actinide", 9, 6, 92, 146, 92, "[Rn] 5f³ 6d¹ 7s²", 1.38, [2, 8, 18, 32, 21, 9, 2], "Colliding neutron stars kilonova r-process nucleosynthesis", "اصطدام النجوم النيوترونية ومسار r في الكيلونوفا", ["Commercial nuclear power plants generating 10% of world electricity", "Naval nuclear aircraft carriers and submarine propulsion", "Depleted uranium high-density military armor protection"], ["محطات الطاقة النووية التجارية التي تنتج 10% من كهرباء العالم", "دفع حاملات الطائرات والغواصات النووية العسكرية", "دروع اليورانيوم المنضب عالية الكثافة للحماية العسكرية"]],
  [93, "Np", "Neptunium", "نبتونيوم", 237.0, "actinide", 9, 7, 93, 144, 93, "[Rn] 5f⁴ 6d¹ 7s²", 1.36, [2, 8, 18, 32, 22, 9, 2], "Transmutation of uranium in nuclear reactors (Oak Ridge)", "تحويل اليورانيوم في المفاعلات النووية (أوك ريدج)", ["Precursor for synthesizing Plutonium-238 space batteries", "Nuclear high-energy neutron detection physics instruments", "Geochemical tracer for radioactive waste repository monitoring"], ["المادة الأولية لتخليق بلوتونيوم-238 لبطاريات الفضاء", "أجهزة كشف النيوترونات عالية الطاقة في الفيزياء النووية", "متتبع جيوكيميائي لمراقبة مستودعات النفايات الإشعاعية"]],
  [94, "Pu", "Plutonium", "بلوتونيوم", 244.0, "actinide", 9, 8, 94, 150, 94, "[Rn] 5f⁶ 7s²", 1.28, [2, 8, 18, 32, 24, 8, 2], "Neutron capture in nuclear reactors (Glenn Seaborg Berkeley)", "الالتقاط النيوتروني بالمفاعلات (غلين سيبورغ بيركلي)", ["Plutonium-238 RTG powering NASA Mars Perseverance Rover & Voyagers", "Nuclear fission deterrent weapons and defense warheads", "Mixed Oxide (MOX) recycled commercial nuclear reactor fuel"], ["بلوتونيوم-238 لتشغيل مسبار ناسا بيرسيفيرانس على المريخ وفوياجر", "رؤوس الردع والأسلحة الدفاعية النووية الانشطارية", "وقود الأكسيد المختلط MOX لتدوير الوقود النووي التجاري"]],
  [95, "Am", "Americium", "أمريسيوم", 243.0, "actinide", 9, 9, 95, 148, 95, "[Rn] 5f⁷ 7s²", 1.30, [2, 8, 18, 32, 25, 8, 2], "Neutron bombardment of plutonium (Manhattan Project 1944)", "قصف البلوتونيوم بالنيوترونات (مشروع مانهاتن 1944)", ["Americium-241 ionization residential home smoke detectors", "Industrial thickness gauging of sheet glass, metal, and plastic", "Portable neutron radiography sources for aircraft inspection"], ["أمريسيوم-241 في كواشف الدخان المنزلية المؤينة لإنقاذ الأرواح", "قياس سماكة صفائح المعادن والزجاج والبلاستيك صناعياً", "أجهزة تصوير النيوترونات لفحص هياكل الطائرات"]],
  [96, "Cm", "Curium", "كوريوم", 247.0, "actinide", 9, 10, 96, 151, 96, "[Rn] 5f⁷ 6d¹ 7s²", 1.30, [2, 8, 18, 32, 25, 9, 2], "Alpha bombardment of plutonium at UC Berkeley (1944)", "قصف البلوتونيوم بجسيمات ألفا في جامعة بيركلي 1944", ["Alpha Particle X-ray Spectrometer (APXS) on Mars exploration rovers", "Radioisotope thermoelectric power for deep-ocean submersibles", "Heavy transuranic target isotope for synthesizing new elements"], ["مطياف ألفا والأشعة السينية APXS على مركبات استكشاف المريخ", "طاقة النظائر المشعة للغواصات في أعماق المحيطات", "هدف تخليق العناصر الأثقل في مسرعات الجسيمات"]],
  [97, "Bk", "Berkelium", "بركليوم", 247.0, "actinide", 9, 11, 97, 150, 97, "[Rn] 5f⁹ 7s²", 1.30, [2, 8, 18, 32, 27, 8, 2], "Americium bombardment at Berkeley Radiation Lab (1949)", "قصف الأمريسيوم في مختبر بيركلي للإشعاع 1949", ["Target material used to synthesize Tennessine (Element 117)", "Scientific research on transuranic magnetic coordination chemistry", "Study of relativistic contractions in the actinide series"], ["الهدف النووي الذي استخدم لتخليق عنصر التينيسين (عنصر 117)", "أبحاث الكيمياء التناسقية المغناطيسية لعناصر ما بعد اليورانيوم", "دراسة الانكماشات النسبية في سلسلة الأكتينيدات"]],
  [98, "Cf", "Californium", "كاليفورنيوم", 251.0, "actinide", 9, 12, 98, 153, 98, "[Rn] 5f¹⁰ 7s²", 1.30, [2, 8, 18, 32, 28, 8, 2], "Alpha bombardment of Curium at UC Berkeley (1950)", "قصف الكوريوم بجسيمات ألفا في بيركلي 1950", ["Californium-252 extremely intense neutron source (170 million n/s/µg)", "Neutron startup source for commercial nuclear power plants", "Prompt Gamma Neutron Activation Analysis for coal & cement scanning"], ["كاليفورنيوم-252 أقوى مصدر نيوتروني معروف (170 مليون نيوترون/ث/ميكروجرام)", "بدء تشغيل المفاعلات النووية التجارية وتغذية النيوترونات", "تحليل التنشيط النيوتروني لفحص جودة الأسمنت والفحم"]],
  [99, "Es", "Einsteinium", "أينشتاينيوم", 252.0, "actinide", 9, 13, 99, 153, 99, "[Rn] 5f¹¹ 7s²", 1.30, [2, 8, 18, 32, 29, 8, 2], "Ivy Mike thermonuclear hydrogen bomb debris at Enewetak (1952)", "حطام القنبلة الهيدروجينية آيفي مايك في إنيويتوك 1952", ["Synthesizing Mendelevium (Element 101) via alpha bombardment", "Investigating actinide contraction and self-radiation damage", "Fundamental nuclear physics properties of superheavy nuclei"], ["تخليق عنصر المندليفيوم (عنصر 101) عبر قذف جسيمات ألفا", "دراسة أضرار الإشعاع الذاتي والانكماش الأكتينيدي", "الخواص الأساسية في الفيزياء النووية للنوى فائقة الثقل"]],
  [100, "Fm", "Fermium", "فيرميوم", 257.0, "actinide", 9, 14, 100, 157, 100, "[Rn] 5f¹² 7s²", 1.30, [2, 8, 18, 32, 30, 8, 2], "Discovered in debris of Ivy Mike thermonuclear detonation (1952)", "اكتشف في مخلفات التفجير النووي الحراري آيفي مايك 1952", ["Heaviest element that can be produced via neutron capture", "Studying spontaneous nuclear fission barrier dynamics", "Advanced actinide separation chemistry research"], ["أثقل عنصر يمكن إنتاجه عن طريق التقاط النيوترونات المتتالية", "دراسة ديناميكيات حواجز الانشطار النووي التلقائي", "أبحاث الكيمياء المتقدمة لفصل الأكتينيدات"]],
  [101, "Md", "Mendelevium", "مندليفيوم", 258.0, "actinide", 9, 15, 101, 157, 101, "[Rn] 5f¹³ 7s²", 1.30, [2, 8, 18, 32, 31, 8, 2], "First element produced one atom at a time (Berkeley 1955)", "أول عنصر ينتج ذرة واحدة في كل مرة (بيركلي 1955)", ["Pioneered single-atom radio-chromatography chemistry", "Proving chemical properties match homologous thulium", "Studying +2 and +3 oxidation state equilibria in aqueous solutions"], ["ريادة كيمياء الكروماتوغرافيا الإشعاعية للذرة الواحدة", "إثبات تطابق الخصائص الكيميائية مع نظيره الثوليوم", "دراسة توازنات حالات الأكسدة +2 و +3 في المحاليل المائية"]],
  [102, "No", "Nobelium", "نوبليوم", 259.0, "actinide", 9, 16, 102, 157, 102, "[Rn] 5f¹⁴ 7s²", 1.30, [2, 8, 18, 32, 32, 8, 2], "Synthesized at JINR Dubna and Lawrence Berkeley Lab (1958-1966)", "خُلِّق في مختبر دوبنا ومختبر بيركلي الوطني (1958-1966)", ["Anomalous chemical stability of the divalent +2 oxidation state", "Testing relativistic effects on filled 5f14 electron shells", "Laser resonance ionization spectroscopy of actinide nuclei"], ["الاستقرار الكيميائي الشاذ لحالة الأكسدة الثنائية +2", "اختبار التأثيرات النسبية على مدارات 5f14 الممتلئة", "التحليل الطيفي للتأين بالرنين الليزري لنوى الأكتينيد"]],
  [103, "Lr", "Lawrencium", "لورنسيوم", 266.0, "actinide", 9, 17, 103, 163, 103, "[Rn] 5f¹⁴ 7s² 7p¹", null, [2, 8, 18, 32, 32, 8, 3], "Synthesized by Albert Ghiorso et al. at Berkeley (1961)", "خُلِّق بواسطة ألبرت غيورسو وفريقه في بيركلي 1961", ["Proved unique [Rn] 5f14 7s2 7p1 relativistic ground configuration", "First measurement of the lowest ionization potential in actinides", "Closing the actinide series and transition to transactinides"], ["إثبات التوزيع النسبي الفريد [Rn] 5f14 7s2 7p1", "أول قياس لأدنى جهد تأين في سلسلة عناصر الأكتينيدات", "ختام سلسلة الأكتينيدات والانتقال إلى ما بعد الأكتينيدات"]],

  // Transactinides / Superheavy elements (Period 7 continued: Cols 4-18)
  [104, "Rf", "Rutherfordium", "رذرفورديوم", 267.0, "transition", 7, 4, 104, 163, 104, "[Rn] 5f¹⁴ 6d² 7s²", null, [2, 8, 18, 32, 32, 10, 2], "JINR Dubna & Lawrence Berkeley National Lab (1964-1969)", "معهد دوبنا للأبحاث النووية ومختبر بيركلي (1964-1969)", ["First superheavy transactinide element explored chemically", "Gas-phase chromatography of volatile chloride RfCl4 compounds", "Confirmation of Group 4 chemical homology with hafnium"], ["أول عنصر فائق الثقل يتم فحصه واختبار كيميائه تجريبياً", "كروماتوغرافيا الطور الغازي لمركبات كلوريد الرذرفورديوم RfCl4", "تأكيد التشابه الكيميائي للمجموعة 4 مع الهافنيوم"]],
  [105, "Db", "Dubnium", "دوبنيوم", 268.0, "transition", 7, 5, 105, 163, 105, "[Rn] 5f¹⁴ 6d³ 7s²", null, [2, 8, 18, 32, 32, 11, 2], "Joint Institute for Nuclear Research (JINR) Dubna (1968-1970)", "المعهد المشترك للأبحاث النووية في دوبنا (1968-1970)", ["Gas-phase halide thermochromatography experiments", "Studying group 5 relativistic effects relative to tantalum", "Testing nuclear fission barrier heights in neutron-deficient actinides"], ["تجارب الكروماتوغرافيا الحرارية لمركبات الهاليد بالطور الغازي", "دراسة التأثيرات النسبية للمجموعة 5 مقارنة بالتانتالوم", "اختبار حواجز الانشطار النووي في نوى الأكتينيدات الثقيلة"]],
  [106, "Sg", "Seaborgium", "سيبورغيوم", 269.0, "transition", 7, 6, 106, 163, 106, "[Rn] 5f¹⁴ 6d⁴ 7s²", null, [2, 8, 18, 32, 32, 12, 2], "Lawrence Berkeley Lab synthesized by Ghiorso & Seaborg (1974)", "مختبر بيركلي بواسطة غيورسو وسيبورغ (1974)", ["First synthesis of a hexacarbonyl superheavy complex Sg(CO)6", "Demonstrating group 6 chemical behavior identical to tungsten", "Validating relativistic density functional quantum predictions"], ["أول تخليق لمركب سداسي الكربونيل لعنصر فائق الثقل Sg(CO)6", "إثبات السلوك الكيميائي للمجموعة 6 المطابق للتنغستن", "التحقق من تنبؤات نظرية الكثافة الوظيفية الكمية النسبية"]],
  [107, "Bh", "Bohrium", "بوريوم", 270.0, "transition", 7, 7, 107, 163, 107, "[Rn] 5f¹⁴ 6d⁵ 7s²", null, [2, 8, 18, 32, 32, 13, 2], "GSI Helmholtz Centre for Heavy Ion Research Darmstadt (1981)", "مركز هلمهولتز لبحوث الأيونات الثقيلة في دارمشتات 1981", ["Gas-phase synthesis of volatile oxychloride BhO3Cl", "Confirming rhenium-like Group 7 relativistic volatility", "Studying alpha decay chains connecting to dubnium and lawrencium"], ["تخليق مركب أوكسي كلوريد البوريوم BhO3Cl بالطور الغازي", "تأكيد تطاير مركبات المجموعة 7 النسبية المشابهة للرينيوم", "دراسة سلاسل تحلل ألفا الممتدة إلى الدوبنيوم واللورنسيوم"]],
  [108, "Hs", "Hassium", "هاسيوم", 277.0, "transition", 7, 8, 108, 169, 108, "[Rn] 5f¹⁴ 6d⁶ 7s²", null, [2, 8, 18, 32, 32, 14, 2], "GSI Helmholtz Darmstadt synthesized by Münzenberg et al. (1984)", "مركز دارمشتات بقيادة بيتر مونتسينبيرغ 1984", ["Synthesis of extremely volatile tetroxide HsO4 on cryogenic surfaces", "Validation of periodic law for superheavy elements at group 8", "Discovery of deformed nuclear shell closures at N=162"], ["تخليق رابع أكسيد الهاسيوم HsO4 وتكثيفه على أسطح التبريد", "إثبات خضوع العناصر فائقة الثقل للجدول الدوري بالمجموعة 8", "اكتشاف انغلاق الأغلفة النووية المشوهة عند عدد نيوترونات N=162"]],
  [109, "Mt", "Meitnerium", "مايتنريوم", 278.0, "transition", 7, 9, 109, 169, 109, "[Rn] 5f¹⁴ 6d⁷ 7s²", null, [2, 8, 18, 32, 32, 15, 2], "GSI Darmstadt named in honor of nuclear physicist Lise Meitner (1982)", "مركز دارمشتات تكريماً لعالمة الفيزياء ليز مايتنر 1982", ["Discovery via single-event detection of Bi-209 + Fe-58 fusion", "First element named after a non-mythological female scientist alone", "Investigating group 9 relativistic electron configuration destabilization"], ["اكتشف عبر رصد حدث فردي لاندماج البزموت-209 مع الحديد-58", "أول عنصر يسمى تكريماً لعالمة فيزياء تاريخية ليز مايتنر", "دراسة زعزعة استقرار التوزيع الإلكتروني النسبي للمجموعة 9"]],
  [110, "Ds", "Darmstadtium", "دارمشتاتيوم", 281.0, "transition", 7, 10, 110, 171, 110, "[Rn] 5f¹⁴ 6d⁹ 7s¹", null, [2, 8, 18, 32, 32, 17, 1], "GSI Helmholtz Centre for Heavy Ion Research Darmstadt (1994)", "مركز هلمهولتز للأيونات الثقيلة في دارمشتات 1994", ["Fusion of Lead-208 target with Nickel-62 ion projectile beam", "Probing relativistic spin-orbit coupling in superheavy atoms", "Decay chain spectroscopy confirming magic nuclear micro-stability"], ["اندماج هدف الرصاص-208 مع حزمة أيونات النيكل-62 بالمسرع", "سبر الترابط المغزلي المداري النسبي في الذرات فائقة الثقل", "مطيافية سلاسل التحلل المؤكدة للاستقرار النووي السحري الجزئي"]],
  [111, "Rg", "Roentgenium", "رونتجينيوم", 282.0, "transition", 7, 11, 111, 171, 111, "[Rn] 5f¹⁴ 6d¹⁰ 7s¹", null, [2, 8, 18, 32, 32, 18, 1], "GSI Helmholtz Darmstadt named after Wilhelm Röntgen (1994)", "مركز دارمشتات تكريماً لمكتشف الأشعة السينية رونتجن 1994", ["Cold fusion reaction using Bismuth-209 target bombarded by Nickel-64", "Studying enormous relativistic contraction of the 7s valence shell", "Predicted to exhibit noble metal properties similar to gold"], ["تفاعل الاندماج البارد لقذف البزموت-209 بحزمة النيكل-64", "دراسة الانكماش النسبي الهائل للمدار 7s التكافؤي", "توقع سلوك معدني نبيل فائق المقاومة للأكسدة شبيه بالذهب"]],
  [112, "Cn", "Copernicium", "كوبرنيسيوم", 285.0, "transition", 7, 12, 112, 173, 112, "[Rn] 5f¹⁴ 6d¹⁰ 7s²", null, [2, 8, 18, 32, 32, 18, 2], "GSI Darmstadt named in honor of astronomer Nicolaus Copernicus (1996)", "مركز دارمشتات تكريماً لعالم الفلك نيكولاس كوبرنيكوس 1996", ["Exhibits noble-gas-like volatility due to relativistic inert 7s2 pair", "Adsorption enthalpy measured atom-by-atom on gold cryo-detectors", "Benchmark for extreme relativistic contraction of electron shells"], ["يظهر تطايراً شبيهاً بالغازات الخاملة بسبب ثبات زوج 7s2 النسبي", "قياس المحتوى الحراري للامتزاز ذرة بذرة على كواشف الذهب", "معيار علمي لاختبار أقصى درجات الانكماش النسبي للإلكترونات"]],
  [113, "Nh", "Nihonium", "نيهونيوم", 286.0, "post-transition", 7, 13, 113, 173, 113, "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", null, [2, 8, 18, 32, 32, 18, 3], "RIKEN Nishina Center in Wako, Japan (Kosuke Morita team 2004)", "مركز ريكين في واكو، اليابان (فريق كوسوكي موريتا 2004)", ["First synthetic element discovered in Asia using cold fusion (Bi+Zn)", "Probing relativistic spin-orbit splitting between 7p1/2 and 7p3/2", "Observed through definitive alpha chains terminating in Mendelevium"], ["أول عنصر مخلق يكتشف في قارة آسيا بالاندماج البارد (Bi+Zn)", "سبر الانشطار النسبي المغزلي المداري بين المدارين 7p1/2 و 7p3/2", "رصد عبر سلاسل تحلل ألفا المؤكدة المنتهية بالمندليفيوم"]],
  [114, "Fl", "Flerovium", "فليروفيوم", 289.0, "post-transition", 7, 14, 114, 175, 114, "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", null, [2, 8, 18, 32, 32, 18, 4], "JINR Dubna & Lawrence Livermore National Laboratory (1998)", "معهد دوبنا النووي ومختبر لورانس ليفرمور الوطني (1998)", ["Close to the predicted center of the nuclear 'Island of Stability'", "Exhibits quasi-noble volatile behavior due to closed 7p1/2 subshell", "Direct proof of relativistic effects altering periodic table trends"], ["يقترب من المركز النظري المتوقع لـ 'جزيرة الاستقرار' النووية", "يظهر سلوكاً شبه نبيل متطايراً لانغلاق الغلاف الفرعي 7p1/2", "دليل مباشر على تغيير التأثيرات النسبية لمسار الجدول الدوري"]],
  [115, "Mc", "Moscovium", "موسكوفيوم", 290.0, "post-transition", 7, 15, 115, 175, 115, "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", null, [2, 8, 18, 32, 32, 18, 5], "JINR Dubna, LLNL, and Oak Ridge National Laboratory (2003)", "معهد دوبنا ومختبر ليفرمور ومختبر أوك ريدج الوطني (2003)", ["Hot fusion reaction bombarding Americium-243 with Calcium-48 ions", "Parent nucleus decaying to Nihonium via high-energy alpha emission", "Studying relativistic ionization potential of pnictogen group 15"], ["تفاعل الاندماج الساخن بقصف أمريسيوم-243 بحزم الكالسيوم-48", "النواة الأم المتحللة للنيهونيوم عبر انبعاث جسيمات ألفا عالية الطاقة", "دراسة جهد التأين النسبي لعناصر مجموعة النيكتوجين 15"]],
  [116, "Lv", "Livermorium", "ليفرموريوم", 293.0, "post-transition", 7, 16, 116, 177, 116, "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", null, [2, 8, 18, 32, 32, 18, 6], "JINR Dubna & Lawrence Livermore National Laboratory (2000)", "معهد دوبنا ومختبر لورانس ليفرمور للأبحاث (2000)", ["Hot fusion of Curium-248 target with high-flux Calcium-48 ions", "Confirmation of alpha decay systematics approaching N=184 shell", "Chemical exploration of chalcogen group 16 relativistic behavior"], ["الاندماج الساخن لهدف الكوريوم-248 مع حزم الكالسيوم-48 الكثيفة", "تأكيد نسقية تحلل ألفا مع الاقتراب من الغلاف السحري N=184", "الاستكشاف الكيميائي لسلوك الكالكوجين النسبي بالمجموعة 16"]],
  [117, "Ts", "Tennessine", "تينيسين", 294.0, "halogen", 7, 17, 117, 177, 117, "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", null, [2, 8, 18, 32, 32, 18, 7], "JINR Dubna, Vanderbilt University, and Oak Ridge (2010)", "معهد دوبنا وجامعة فاندربيلت ومختبر أوك ريدج (2010)", ["Synthesized using 22 mg of rare Berkelium-249 produced at ORNL", "Superheavy halogen predicted to exhibit semi-metallic behavior", "Final halogen synthesized in the 7th row of the periodic table"], ["خُلِّق باستخدام 22 ملغرام من البركليوم-249 النادر المنتج في أوك ريدج", "هالوجين فائق الثقل يتوقع إظهاره سلوكاً شبه معدني بسبب النسبية", "آخر هالوجين تم تخليقه في الصف السابع من الجدول الدوري"]],
  [118, "Og", "Oganesson", "أوغانيسون", 294.0, "noble", 7, 18, 118, 176, 118, "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", null, [2, 8, 18, 32, 32, 18, 8], "JINR Dubna & LLNL named after academician Yuri Oganessian (2002)", "معهد دوبنا وليفرمور تكريماً للبروفيسور يوري أوغانيسيان (2002)", ["Heaviest element officially recognized on the periodic table", "Relativistic Thomas-Fermi electron smearing creates uniform Fermi gas", "Predicted to be a solid semiconductor at room temperature, not a gas"], ["أثقل عنصر كيميائي معترف به رسمياً في الجدول الدوري", "تلاشي التميز المداري للإلكترونات نسبياً لتشكل غاز فيرمي الموحد", "يتوقع أن يكون مادة شبه موصلة صلبة في حرارة الغرفة وليس غازاً"]],
];

console.log(`Loaded ${elementsRaw.length} raw elements.`);

const elements = elementsRaw.map((item) => {
  const [num, sym, nameEn, nameAr, mass, cat, row, col, p, n, e, config, eneg, shells, origin, originAr, uses, usesAr] = item;
  const stringsCount = 4 * p + 3 * n;
  return {
    num,
    sym,
    nameEn,
    nameAr,
    mass,
    cat,
    row,
    col,
    p,
    n,
    e,
    config,
    eneg,
    shells,
    origin,
    originAr,
    uses,
    usesAr,
    stringsCount,
  };
});

const tsCode = `export interface ElementData {
  num: number;
  sym: string;
  nameEn: string;
  nameAr: string;
  mass: number;
  cat: 'alkali' | 'alkaline' | 'transition' | 'post-transition' | 'metalloid' | 'nonmetal' | 'halogen' | 'noble' | 'lanthanide' | 'actinide';
  row: number;
  col: number;
  p: number;
  n: number;
  e: number;
  config: string;
  eneg: number | null;
  shells: number[];
  origin: string;
  originAr: string;
  uses: string[];
  usesAr: string[];
  stringsCount: number; // 4Z + 3N
}

export const ELEMENTS: ElementData[] = ${JSON.stringify(elements, null, 2)};

export const ELEMENT_MAP: Record<number, ElementData> = ELEMENTS.reduce((acc, el) => {
  acc[el.num] = el;
  return acc;
}, {} as Record<number, ElementData>);

export const CATEGORY_COLORS: Record<ElementData['cat'], { hex: string; bg: string; border: string; nameEn: string; nameAr: string }> = {
  alkali: {
    hex: '#f43f5e',
    bg: 'bg-rose-500/20',
    border: 'border-rose-500',
    nameEn: 'Alkali Metal',
    nameAr: 'فلز قلوي',
  },
  alkaline: {
    hex: '#fb923c',
    bg: 'bg-orange-500/20',
    border: 'border-orange-500',
    nameEn: 'Alkaline Earth',
    nameAr: 'فلز قلوي ترابي',
  },
  transition: {
    hex: '#f59e0b',
    bg: 'bg-amber-500/20',
    border: 'border-amber-500',
    nameEn: 'Transition Metal',
    nameAr: 'فلز انتقالي',
  },
  'post-transition': {
    hex: '#eab308',
    bg: 'bg-yellow-500/20',
    border: 'border-yellow-500',
    nameEn: 'Post-Transition Metal',
    nameAr: 'فلز ما بعد الانتقالي',
  },
  metalloid: {
    hex: '#84cc16',
    bg: 'bg-lime-500/20',
    border: 'border-lime-500',
    nameEn: 'Metalloid',
    nameAr: 'شبه فلز',
  },
  nonmetal: {
    hex: '#06b6d4',
    bg: 'bg-cyan-500/20',
    border: 'border-cyan-500',
    nameEn: 'Reactive Nonmetal',
    nameAr: 'لا فلز تفاعلي',
  },
  halogen: {
    hex: '#3b82f6',
    bg: 'bg-blue-500/20',
    border: 'border-blue-500',
    nameEn: 'Halogen',
    nameAr: 'هالوجين',
  },
  noble: {
    hex: '#a855f7',
    bg: 'bg-purple-500/20',
    border: 'border-purple-500',
    nameEn: 'Noble Gas',
    nameAr: 'غاز نبيل',
  },
  lanthanide: {
    hex: '#ec4899',
    bg: 'bg-pink-500/20',
    border: 'border-pink-500',
    nameEn: 'Lanthanide',
    nameAr: 'لانثانيد',
  },
  actinide: {
    hex: '#10b981',
    bg: 'bg-emerald-500/20',
    border: 'border-emerald-500',
    nameEn: 'Actinide',
    nameAr: 'أكتينيد',
  },
};
`;

const outputPath = path.join(__dirname, '..', 'data', 'elementsData.ts');
fs.writeFileSync(outputPath, tsCode, 'utf8');
console.log('Successfully wrote data/elementsData.ts with all 118 elements!');
